# fly.toml app configuration file generated for tanngo-app-clean-v2 on 2025-08-04T09:52:32+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'tanngo-app-clean-v2'
primary_region = 'nrt'

[build]
 command = "flask db upgrade"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
  
  # ▼▼▼ このヘルスチェックのセクションを追記 ▼▼▼
  [[http_service.checks]]
    interval = "15s"
    timeout = "10s"
    grace_period = "90s"
    method = "get"
    path = "/"


[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
