# fly.toml app configuration file generated for tanngo-app-clean-v2 on 2025-08-04T09:52:32+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'tanngo-app-clean-v2'
primary_region = 'nrt'

[build]
  command = "flask db upgrade"

[http_service]
  # ... 既存の設定はそのまま ...
  
  # ▼▼▼ このヘルスチェックのセクションを追記 ▼▼▼
  [[http_service.checks]]
    interval = "15s"
    timeout = "10s"
    grace_period = "30s"
    method = "get"
    path = "/"


[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
